name: .NET Core Build with Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Install dependencies
      run: dotnet restore

      # build project
    - name: Build
      run: dotnet build .PruebaCsvImporter_CristianTorres/CsvImporter/CsvImporter.sln --configuration $config --no-restore
      
      # run tests project
    - name: Tests      
      run: dotnet test   --configuration 
